### ISSUE TITLE
RangoMania

### ISSUE THREAD

**Issue by walberbeltrame** [ateliedeideias/crias-conscientes#5]
![RangoMania Gamification Canvas Model (2)](https://user-images.githubusercontent.com/73710893/99098885-698d2500-25b8-11eb-89f7-967e21c7cae3.jpg)

https://docs.google.com/drawings/d/1UR_WHVV5DZ614J8-3zmqts7uIvyGD5fOi_mHmiDjPfw/edit?usp=sharing

**Comment by gustavobelloo** [comment]
![RangoMania Gamification Canvas Model (2)](https://user-images.githubusercontent.com/73710893/99099073-a6f1b280-25b8-11eb-9708-4ff790a209f6.jpg)

https://docs.google.com/drawings/d/1UR_WHVV5DZ614J8-3zmqts7uIvyGD5fOi_mHmiDjPfw/edit?usp=sharing
