### ISSUE TITLE
Sewerage Rebellion

### ISSUE THREAD

**Issue by walberbeltrame** [ateliedeideias/crias-conscientes#6]

**Comment by leonardocam1** [comment]
Link do Gamification Canvas
https://docs.google.com/drawings/d/1YbGDhbsmonBY6kyRlm9K0gQRe30b7aYYi8idf-Uyf8I/edit?usp=sharing

**Comment by leonardocam1** [comment]
![image](https://user-images.githubusercontent.com/74058582/99037004-8ea27900-2561-11eb-91af-26f9553cfcce.png)

**Comment by leonardocam1** [comment]
![image](https://user-images.githubusercontent.com/74058582/99037040-ac6fde00-2561-11eb-8e28-3af99bfd8ad8.png)
